### ISSUE TITLE
Install Argo Workflow on ADC k8s cluster

### ISSUE THREAD

**Issue by mfisher87** [QGreenland-Net/argo-exploration#2]
https://argo-workflows.readthedocs.io/en/latest/installation/#production-installation

We think we want "cluster install" which installs Argo Workflows into e.g. "argo" namespace, but you can still run workflows in other namespaces on the cluster, e.g. our "qgnet" namespace.

**Comment by trey-stafford** [comment]
We plan to use Bitnami Helm installation for Argo.

**Comment by rushirajnenuji** [comment]
Completed [example workflow](https://github.com/rushirajnenuji/dataone-gse/commit/c66c89be356820c16dccf3edbc6f50a639565106)
